language: node_js
node_js:
  - "14"

addons:
  sonarcloud:
    organization: "micgro42-github"
    token:
      secure: $SONARCLOUD_TOKEN

install:
  - yarn install

script:
  - yarn lint
  - yarn test:unit --coverage
  - sonar-scanner

after_success:
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist/
    github_token: $GITHUB_TOKEN
    verbose: true
    on:
      branch: master
